# Site settings
title: Paul Speshock 
email: pauls18@vt.edu
name: Paul Speshock

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/speshock
 - title: StackOverflow
   url: 
 - title: DZone
   url: 
 - title: LinkedIn
   url: 

#Any buzzword skills you want to include
skills:
 - Python
 - Java
 - Linux
 - Test Driven Development
 - Tensorflow
 - Machine learning
 - Artificial Intelligence
 - IT Security
 - Digital Forensics
 - IoT
 - Raspberry pi
 - Agile
 - SQL
 - Database Design
 - AWS
 - Hadoop
 - Tableau

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Graduate Assistant
   start: 2018
   end: Ongoing
   employer: Virginia Tech
   description: Assist both the MBA and IT programs in a dual role. Created a functional relational database for the MIT program to track student progress for reporting  metrics used by US News & World Report.  Created Python data funneling scripts to automate adding data to the database. Use Tableau to create data visualizations and analytics.
 - title: Marvel Character Performer
   start: 2017
   end: 2017
   employer: Hong Kong Disneyland
   description: Opening team for the Marvel Super Hero Summer Event. Portrayed Thor and Star-Lord in the interactive walkthrough attraction, Dimensions of Danger. Portrayed Captain America for guest meet and greets.
   link: <iframe width="560" height="315" src="https://www.youtube.com/embed/e-c959ruUAg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
 - title: Outdoor Adventure Specialist
   start: 2016
   end: 2017
   employer: Inner Quest
   description: Inner Quest is an outdoor experiential educational organization. <br/> I was responsible for facilitating groups on adventure trips and throughout daily challenge course programs. Maintained organized safety procedures and responsible for group itinerary. Broad customer service/people skills required.  
 - title: Youth Activities Staff
   start: 2014
   end: 2015
   employer: Royal Caribbean
   description: Managed activities on a daily basis for 20-100 people at a time. Worked 7 days a week for two 5 month contracts. Traveled the world.

#Education is required
education:
 - level: Masters
   date: 2020
   subject: Information Technology
   school: Virginia Tech

#Fun Experiences are optional
experiences:
 - title: Disneyland Hong Kong Marvel Character Performer
   optionalvideo: <iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

#This section is optional (as is the image link below)
# coursera:
 #  profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
  # courses:
   # - title: Functional Programming Principles in Scala
    #  link: https://www.coursera.org/course/progfun
     # optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      #date: September 16, 2013
   # - title: Algorithms Design and Analysis, Part 1
    #  link: https://www.coursera.org/specializations/algorithms
     # optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      #date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
 #  profileurl: https://speakerdeck.com/robhinds
  # talks:
   # - title: Product Management for Engineers
    #  speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
     # conference: API Conference, Berlin 2018
    #- title: Agile Machine Learning - from Theory to Production
     # speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      #conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
#github:
# - robhinds/robhinds.github.io
# - robhinds/ScaLambda
# - robhinds/opinionated-akka-http
# - robhinds/food2vec
# - robhinds/microservices
# - robhinds/spring-social-geeklist
# - robhinds/spring-social-stackoverflow
# - robhinds/genotype
# - robhinds/footweets
# - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
#  I am an engineer with 15 years experience working in technology. I have primarily worked on the JVM, but have worked across a broad range of technologies thereon: Java, Groovy, Android, Coldfusion and most recently Scala. As well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of javascript technologies over the years, through jQuery, extjs, knockout, backbone and most recently to React. <br/><br/>
#  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code (having worked across differing languages on the JVM, I recognise that good code is contextual).<br/><br/>
#  I have worked in large scale consultancy roles across Europe as well as a mix of startup experience (including one that was acquired) and I am currently the Chief Technology Officer at a legal-tech startup called <a href="https://www.basementcrowd.com" target="_blank">Basement Crowd</a> where we are building innovative products to serve the legal industry.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
#   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
#   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
#   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
#   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
#   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
#   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
#   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
#   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
#   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
