# Site settings
title: Paul Speshock 
email: pauls18@vt.edu
name: Paul Speshock

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/speshock
 - title: StackOverflow
   url: 
 - title: DZone
   url: 
 - title: LinkedIn
   url: 

#Any buzzword skills you want to include
skills:
 - Python
 - Java
 - Linux
 - Test Driven Development
 - Tensorflow
 - Machine learning
 - Artificial Intelligence
 - IT Security
 - Digital Forensics
 - IoT
 - Raspberry pi
 - Agile
 - SQL
 - Database Design
 - AWS
 - Hadoop
 - Tableau

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: CTO
   start: 2017
   end: Ongoing
   employer: Basement Crowd
   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
 - title: Senior Engineer
   start: 2016
   end: 2017
   employer: Emerald Street Ventures
   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
 - title: Senior Engineer
   start: 2012
   end: 2016
   employer: Covestor
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Masters
   date: 2020
   subject: Information Technology
   school: Virginia Tech

#This section is optional (as is the image link below)
# coursera:
 #  profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
  # courses:
   # - title: Functional Programming Principles in Scala
    #  link: https://www.coursera.org/course/progfun
     # optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      #date: September 16, 2013
   # - title: Algorithms Design and Analysis, Part 1
    #  link: https://www.coursera.org/specializations/algorithms
     # optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      #date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
 #  profileurl: https://speakerdeck.com/robhinds
  # talks:
   # - title: Product Management for Engineers
    #  speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
     # conference: API Conference, Berlin 2018
    #- title: Agile Machine Learning - from Theory to Production
     # speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      #conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
#github:
# - robhinds/robhinds.github.io
# - robhinds/ScaLambda
# - robhinds/opinionated-akka-http
# - robhinds/food2vec
# - robhinds/microservices
# - robhinds/spring-social-geeklist
# - robhinds/spring-social-stackoverflow
# - robhinds/genotype
# - robhinds/footweets
# - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I am a graduate of Virginia Tech's Master of Information Technology program excited about starting a career in the tech industry. I have primarily worked with Python and enjoy Machine Learning and IoT projects.  While completing my degree, I worked on Artificial Intelligence and computure vision projects.  Most recently,  I worked to create a traffic light detection algorithm using a Faster Inception V2 R-CNN model.  I have also engaged in Java development using the JVM to make simple interactive games like tetris and Adventure. <br/><br/>
  My two main focusses are Cybersecurity and Artificial Intelligence.  I want to eventually bridge the gap between those two interests as a career.  My other interest is harnessing databases to improve business intelligence with analytics.<br/><br/>
  I currently am a Graduate Assistant at Virginia Tech and will be a Distance Learning Instructor for a Healthcare Database Course being taught at Virginia Tech during Summer 2020.

#Fun Experiences are optional
experiences: |
   <strong>Disney</strong>: Disneyland Hong Kong Marvel Character Performer

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Java</strong>: I am familiar with Java Test Driven Development using JUnit along with a number of other Java API’s and frameworks. My IDE of choice is Eclipse. <br/><br/>
   <strong>Python</strong> I have used Python for a number of different use-cases.  Some examples include funneling data between Excel Sheets and a MySQL database, networking applications like video streaming, Machine Learning applications, creating rainbow tables, and much more.  It is my go to programming language to solve tasks. <br/><br/>
   <strong>Tensorflow</strong>: I have primarily used Tensorflow for ML projects focussing on object detection using my own system. An example would be the creation of a model that I tweaked that can detect traffic lights in real time running on a Raspberry pi.<br/><br/>
#   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
#   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
#   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
#   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
#   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
